### ISSUE TITLE
Improve responsive layout in "Trampos"

### ISSUE THREAD

**Issue by bpassos** [zofepod/zofe#93]

**Comment by vcavalcante** [comment]
Hoje a página está dando scroll no mobile, eu fiz um pull request para o trampos para arrumar isso, como vi que é um repositório diferente, não sei se vocês estão olhando para os pull requests que estão sendo feitos lá.
A alteração é simples para pelo menos ficar usável:

````css
.closed:after {
  position: absolute;
  display: block;
  top: 20px;
  left: 0;
  width: 100%; /*alterado*/
  height: 121px;
  border: 0;
  border-radius: 0;
  box-shadow: unset;
  background: transparent url('/trampos/assets/images/vaga-preenchida.png') no-repeat;
  background-size: 100% 100%; /*adicionado*/
}
````
